image: "registry.cn-hangzhou.aliyuncs.com/engintime/ubuntu_16.04_program:latest"

stages:
  - make
  - code_analysis  

variables:
  MAINCLASSNAME: "Mp3Player.jar"

.codecode-runner: &codecode-runner
  tags:
    - ubuntu-16.04
    - short-job

make:
  stage: make
  <<: *codecode-runner
  script:
    - java -version
    - mkdir bin
    - javac -encoding utf-8 -d bin src/com/engintime/programming/simplemp3player/*.java
    - jar cvfm ${MAINCLASSNAME} MANIFEST.MF -C bin/ .  
    - execscore.sh 60
  only: 
    - master 
    
code_analysis:
  stage: code_analysis
  <<: *codecode-runner
  script:
    - mvn --batch-mode verify sonar:sonar -Dsonar.projectKey=ProjectKey-$CI_PROJECT_ID -Dsonar.projectName=$CI_PROJECT_NAME -Dsonar.links.homepage=$CI_PROJECT_URL -Dsonar.host.url=$SONAR_URL -Dsonar.login=$SONAR_LOGIN -Dsonar.gitlab.commit_sha=$CI_COMMIT_SHA -Dsonar.gitlab.ref_name=$CI_COMMIT_REF_NAME -Dsonar.gitlab.project_id=$CI_PROJECT_ID -Dsonar.gitlab.url=$CODECODE_PROTOCOL$CODECODE_DOMAIN
  allow_failure: true
  only:
    - master
    
  